{
 "title": "Energy usage",
 "time": { "from": "2023-01-08T23:00:00.000Z", "to": "2023-02-04T23:00:00.000Z" },
 "panels": [
  {
   "title": "Energy usage per day kWh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time, import, export * -1 as export, netto\nFROM main.main_connection\nORDER BY time asc",
     "rawQueryText": "SELECT time, import, export * -1 as export, netto\nFROM main.main_connection\nORDER BY time asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Water usage per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT time, water FROM main.water\nORDER BY time asc",
     "rawQueryText": "SELECT time, water FROM main.water\nORDER BY time asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Gas usage per day m3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT time, gas \nFROM main.gas\nORDER BY time asc",
     "rawQueryText": "SELECT time, gas \nFROM main.gas\nORDER BY time asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}